// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/wellknown/oauth.proto

package wellknown

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OAuthConfiguration - Defines and well known endpoints in relation to OAuth
type OAuthConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// issuer - The issuer defined by the API structure
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty" bson:"issuer"` // @gotags: bson:"issuer"
	// authorization_endpoint - The authorization endpoint that can be used with Authorization Code Flow
	AuthorizationEndpoint string `protobuf:"bytes,2,opt,name=authorization_endpoint,json=authorizationEndpoint,proto3" json:"authorization_endpoint,omitempty" bson:"authorization_endpoint"` // @gotags: bson:"authorization_endpoint"
	// token_endpoint - Defines the endpoint that allows tokens to be retrieved at
	TokenEndpoint string `protobuf:"bytes,3,opt,name=token_endpoint,json=tokenEndpoint,proto3" json:"token_endpoint,omitempty" bson:"token_endpoint"` // @gotags: bson:"token_endpoint"
	// revocation_endpoint - Defines the endpoint that allows tokens to be revoked at
	RevocationEndpoint string `protobuf:"bytes,4,opt,name=revocation_endpoint,json=revocationEndpoint,proto3" json:"revocation_endpoint,omitempty" bson:"revocation_endpoint"` // @gotags: bson:"revocation_endpoint"
	// introspection_endpoint - Defines the endpoint that tokens can be inspected/validated at
	IntrospectionEndpoint string `protobuf:"bytes,5,opt,name=introspection_endpoint,json=introspectionEndpoint,proto3" json:"introspection_endpoint,omitempty" bson:"introspection_endpoint"` // @gotags: bson:"introspection_endpoint"
	// jwks_uri - The URI that OIDC exposes JWKS information for signing RS256 (id) tokens
	JwksUri       string `protobuf:"bytes,6,opt,name=jwks_uri,json=jwksUri,proto3" json:"jwks_uri,omitempty" bson:"jwks_uri"` // @gotags: bson:"jwks_uri"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthConfiguration) Reset() {
	*x = OAuthConfiguration{}
	mi := &file_proto_wellknown_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthConfiguration) ProtoMessage() {}

func (x *OAuthConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wellknown_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthConfiguration.ProtoReflect.Descriptor instead.
func (*OAuthConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_wellknown_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *OAuthConfiguration) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *OAuthConfiguration) GetAuthorizationEndpoint() string {
	if x != nil {
		return x.AuthorizationEndpoint
	}
	return ""
}

func (x *OAuthConfiguration) GetTokenEndpoint() string {
	if x != nil {
		return x.TokenEndpoint
	}
	return ""
}

func (x *OAuthConfiguration) GetRevocationEndpoint() string {
	if x != nil {
		return x.RevocationEndpoint
	}
	return ""
}

func (x *OAuthConfiguration) GetIntrospectionEndpoint() string {
	if x != nil {
		return x.IntrospectionEndpoint
	}
	return ""
}

func (x *OAuthConfiguration) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

var File_proto_wellknown_oauth_proto protoreflect.FileDescriptor

const file_proto_wellknown_oauth_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/wellknown/oauth.proto\x12\twellknown\"\x8d\x02\n" +
	"\x12OAuthConfiguration\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x125\n" +
	"\x16authorization_endpoint\x18\x02 \x01(\tR\x15authorizationEndpoint\x12%\n" +
	"\x0etoken_endpoint\x18\x03 \x01(\tR\rtokenEndpoint\x12/\n" +
	"\x13revocation_endpoint\x18\x04 \x01(\tR\x12revocationEndpoint\x125\n" +
	"\x16introspection_endpoint\x18\x05 \x01(\tR\x15introspectionEndpoint\x12\x19\n" +
	"\bjwks_uri\x18\x06 \x01(\tR\ajwksUriB8Z6github.com/stevezaluk/credstack-models/proto/wellknownb\x06proto3"

var (
	file_proto_wellknown_oauth_proto_rawDescOnce sync.Once
	file_proto_wellknown_oauth_proto_rawDescData []byte
)

func file_proto_wellknown_oauth_proto_rawDescGZIP() []byte {
	file_proto_wellknown_oauth_proto_rawDescOnce.Do(func() {
		file_proto_wellknown_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wellknown_oauth_proto_rawDesc), len(file_proto_wellknown_oauth_proto_rawDesc)))
	})
	return file_proto_wellknown_oauth_proto_rawDescData
}

var file_proto_wellknown_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_wellknown_oauth_proto_goTypes = []any{
	(*OAuthConfiguration)(nil), // 0: wellknown.OAuthConfiguration
}
var file_proto_wellknown_oauth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wellknown_oauth_proto_init() }
func file_proto_wellknown_oauth_proto_init() {
	if File_proto_wellknown_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wellknown_oauth_proto_rawDesc), len(file_proto_wellknown_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wellknown_oauth_proto_goTypes,
		DependencyIndexes: file_proto_wellknown_oauth_proto_depIdxs,
		MessageInfos:      file_proto_wellknown_oauth_proto_msgTypes,
	}.Build()
	File_proto_wellknown_oauth_proto = out.File
	file_proto_wellknown_oauth_proto_goTypes = nil
	file_proto_wellknown_oauth_proto_depIdxs = nil
}
