// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/wellknown/oidc.proto

package wellknown

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OIDCConfiguration - Defines common endpoints in OAuth and OIDC
type OIDCConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// issuer - The issuer defined by the API structure
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty" bson:"issuer"` // @gotags: bson:"issuer"
	// authorization_endpoint - The authorization endpoint that can be used with Authorization Code Flow
	AuthorizationEndpoint string `protobuf:"bytes,2,opt,name=authorization_endpoint,json=authorizationEndpoint,proto3" json:"authorization_endpoint,omitempty" bson:"authorization_endpoint"` // @gotags: bson:"authorization_endpoint"
	// token_endpoint - Defines the endpoint that allows tokens to be retrieved at
	TokenEndpoint string `protobuf:"bytes,3,opt,name=token_endpoint,json=tokenEndpoint,proto3" json:"token_endpoint,omitempty" bson:"token_endpoint"` // @gotags: bson:"token_endpoint"
	// userinfo_endpoint - Defines the endpoint where ID Tokens can be exchanged for user information
	UserinfoEndpoint string `protobuf:"bytes,4,opt,name=userinfo_endpoint,json=userinfoEndpoint,proto3" json:"userinfo_endpoint,omitempty" bson:"userinfo_endpoint"` // @gotags: bson:"userinfo_endpoint"
	// jwks_uri - The URI that OIDC exposes JWKS information for signing RS256 (id) tokens
	JwksUri string `protobuf:"bytes,5,opt,name=jwks_uri,json=jwksUri,proto3" json:"jwks_uri,omitempty" bson:"jwks_uri"` // @gotags: bson:"jwks_uri"
	// end_session_endpoint - Defines the endpoint where users can logout of there existing session
	EndSessionEndpoint string `protobuf:"bytes,6,opt,name=end_session_endpoint,json=endSessionEndpoint,proto3" json:"end_session_endpoint,omitempty" bson:"end_session_endpoint"` // @gotags: bson:"end_session_endpoint"
	// registration_endpoint - Defines the endpoint where new users can register an account
	RegistrationEndpoint string `protobuf:"bytes,7,opt,name=registration_endpoint,json=registrationEndpoint,proto3" json:"registration_endpoint,omitempty" bson:"registration_endpoint"` // @gotags: bson:"registration_endpoint"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OIDCConfiguration) Reset() {
	*x = OIDCConfiguration{}
	mi := &file_proto_wellknown_oidc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCConfiguration) ProtoMessage() {}

func (x *OIDCConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wellknown_oidc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCConfiguration.ProtoReflect.Descriptor instead.
func (*OIDCConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_wellknown_oidc_proto_rawDescGZIP(), []int{0}
}

func (x *OIDCConfiguration) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *OIDCConfiguration) GetAuthorizationEndpoint() string {
	if x != nil {
		return x.AuthorizationEndpoint
	}
	return ""
}

func (x *OIDCConfiguration) GetTokenEndpoint() string {
	if x != nil {
		return x.TokenEndpoint
	}
	return ""
}

func (x *OIDCConfiguration) GetUserinfoEndpoint() string {
	if x != nil {
		return x.UserinfoEndpoint
	}
	return ""
}

func (x *OIDCConfiguration) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

func (x *OIDCConfiguration) GetEndSessionEndpoint() string {
	if x != nil {
		return x.EndSessionEndpoint
	}
	return ""
}

func (x *OIDCConfiguration) GetRegistrationEndpoint() string {
	if x != nil {
		return x.RegistrationEndpoint
	}
	return ""
}

var File_proto_wellknown_oidc_proto protoreflect.FileDescriptor

const file_proto_wellknown_oidc_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/wellknown/oidc.proto\x12\twellknown\"\xb8\x02\n" +
	"\x11OIDCConfiguration\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x125\n" +
	"\x16authorization_endpoint\x18\x02 \x01(\tR\x15authorizationEndpoint\x12%\n" +
	"\x0etoken_endpoint\x18\x03 \x01(\tR\rtokenEndpoint\x12+\n" +
	"\x11userinfo_endpoint\x18\x04 \x01(\tR\x10userinfoEndpoint\x12\x19\n" +
	"\bjwks_uri\x18\x05 \x01(\tR\ajwksUri\x120\n" +
	"\x14end_session_endpoint\x18\x06 \x01(\tR\x12endSessionEndpoint\x123\n" +
	"\x15registration_endpoint\x18\a \x01(\tR\x14registrationEndpointB7Z5github.com/credstack/credstack-models/proto/wellknownb\x06proto3"

var (
	file_proto_wellknown_oidc_proto_rawDescOnce sync.Once
	file_proto_wellknown_oidc_proto_rawDescData []byte
)

func file_proto_wellknown_oidc_proto_rawDescGZIP() []byte {
	file_proto_wellknown_oidc_proto_rawDescOnce.Do(func() {
		file_proto_wellknown_oidc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wellknown_oidc_proto_rawDesc), len(file_proto_wellknown_oidc_proto_rawDesc)))
	})
	return file_proto_wellknown_oidc_proto_rawDescData
}

var file_proto_wellknown_oidc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_wellknown_oidc_proto_goTypes = []any{
	(*OIDCConfiguration)(nil), // 0: wellknown.OIDCConfiguration
}
var file_proto_wellknown_oidc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wellknown_oidc_proto_init() }
func file_proto_wellknown_oidc_proto_init() {
	if File_proto_wellknown_oidc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wellknown_oidc_proto_rawDesc), len(file_proto_wellknown_oidc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wellknown_oidc_proto_goTypes,
		DependencyIndexes: file_proto_wellknown_oidc_proto_depIdxs,
		MessageInfos:      file_proto_wellknown_oidc_proto_msgTypes,
	}.Build()
	File_proto_wellknown_oidc_proto = out.File
	file_proto_wellknown_oidc_proto_goTypes = nil
	file_proto_wellknown_oidc_proto_depIdxs = nil
}
