// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/request/introspect.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenIntrospectRequest - Represents an end-user request to the /oauth/introspect endpoint
type TokenIntrospectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token - The token that the user wishes to introspect
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty" bson:"token"` // @gotags: bson:"token"
	// token_type_hint - A hint that assists the server in what token is being passed. Can be: access_token, refresh_token
	TokenTypeHint string `protobuf:"bytes,3,opt,name=token_type_hint,json=tokenTypeHint,proto3" json:"token_type_hint,omitempty" bson:"token_type_hint"` // @gotags: bson:"token_type_hint"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenIntrospectRequest) Reset() {
	*x = TokenIntrospectRequest{}
	mi := &file_proto_request_introspect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIntrospectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIntrospectRequest) ProtoMessage() {}

func (x *TokenIntrospectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_request_introspect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIntrospectRequest.ProtoReflect.Descriptor instead.
func (*TokenIntrospectRequest) Descriptor() ([]byte, []int) {
	return file_proto_request_introspect_proto_rawDescGZIP(), []int{0}
}

func (x *TokenIntrospectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenIntrospectRequest) GetTokenTypeHint() string {
	if x != nil {
		return x.TokenTypeHint
	}
	return ""
}

var File_proto_request_introspect_proto protoreflect.FileDescriptor

const file_proto_request_introspect_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/request/introspect.proto\x12\x05token\"V\n" +
	"\x16TokenIntrospectRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12&\n" +
	"\x0ftoken_type_hint\x18\x03 \x01(\tR\rtokenTypeHintB5Z3github.com/credstack/credstack-models/proto/requestb\x06proto3"

var (
	file_proto_request_introspect_proto_rawDescOnce sync.Once
	file_proto_request_introspect_proto_rawDescData []byte
)

func file_proto_request_introspect_proto_rawDescGZIP() []byte {
	file_proto_request_introspect_proto_rawDescOnce.Do(func() {
		file_proto_request_introspect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_request_introspect_proto_rawDesc), len(file_proto_request_introspect_proto_rawDesc)))
	})
	return file_proto_request_introspect_proto_rawDescData
}

var file_proto_request_introspect_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_request_introspect_proto_goTypes = []any{
	(*TokenIntrospectRequest)(nil), // 0: token.TokenIntrospectRequest
}
var file_proto_request_introspect_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_request_introspect_proto_init() }
func file_proto_request_introspect_proto_init() {
	if File_proto_request_introspect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_request_introspect_proto_rawDesc), len(file_proto_request_introspect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_request_introspect_proto_goTypes,
		DependencyIndexes: file_proto_request_introspect_proto_depIdxs,
		MessageInfos:      file_proto_request_introspect_proto_msgTypes,
	}.Build()
	File_proto_request_introspect_proto = out.File
	file_proto_request_introspect_proto_goTypes = nil
	file_proto_request_introspect_proto_depIdxs = nil
}
