// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/request/login.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// email - The primary email address for the user. Must be unique
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// password - The plain text password for the user. Will be hashed on the server-side using ArgonV2ID
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// mfaCode - The user's multifactor authentication code generated on there device
	MfaCode       uint32 `protobuf:"varint,3,opt,name=mfaCode,proto3" json:"mfaCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_request_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_request_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_request_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetMfaCode() uint32 {
	if x != nil {
		return x.MfaCode
	}
	return 0
}

var File_proto_request_login_proto protoreflect.FileDescriptor

const file_proto_request_login_proto_rawDesc = "" +
	"\n" +
	"\x19proto/request/login.proto\x12\arequest\"Z\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\amfaCode\x18\x03 \x01(\rR\amfaCodeB6Z4github.com/stevezaluk/credstack-models/proto/requestb\x06proto3"

var (
	file_proto_request_login_proto_rawDescOnce sync.Once
	file_proto_request_login_proto_rawDescData []byte
)

func file_proto_request_login_proto_rawDescGZIP() []byte {
	file_proto_request_login_proto_rawDescOnce.Do(func() {
		file_proto_request_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_request_login_proto_rawDesc), len(file_proto_request_login_proto_rawDesc)))
	})
	return file_proto_request_login_proto_rawDescData
}

var file_proto_request_login_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_request_login_proto_goTypes = []any{
	(*LoginRequest)(nil), // 0: request.LoginRequest
}
var file_proto_request_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_request_login_proto_init() }
func file_proto_request_login_proto_init() {
	if File_proto_request_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_request_login_proto_rawDesc), len(file_proto_request_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_request_login_proto_goTypes,
		DependencyIndexes: file_proto_request_login_proto_depIdxs,
		MessageInfos:      file_proto_request_login_proto_msgTypes,
	}.Build()
	File_proto_request_login_proto = out.File
	file_proto_request_login_proto_goTypes = nil
	file_proto_request_login_proto_depIdxs = nil
}
