// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/request/register.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRegisterRequest - Provides a way for user's to register there accounts on a service.
// Any values not provided in this request must be modified after user-registration
type UserRegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// email - The primary email address for the user. Must be unique
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" bson:"email" query:"email"` // @gotags: bson:"email" query:"email"
	// username - The username of the user. Does not need to be unique as primary lookup for the user is done via userId
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty" bson:"username" query:"username"` // @gotags: bson:"username" query:"username"
	// password - The plain text password for the user. Will be hashed on the server-side using ArgonV2ID
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty" bson:"password" query:"password"` // @gotags: bson:"password" query:"password"
	// phone_number - The users phone number in the following format +1800-555-555
	PhoneNumber   string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty" bson:"phone_number" query:"phone_number"` // @gotags: bson:"phone_number" query:"phone_number"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterRequest) Reset() {
	*x = UserRegisterRequest{}
	mi := &file_proto_request_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterRequest) ProtoMessage() {}

func (x *UserRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_request_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterRequest.ProtoReflect.Descriptor instead.
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_request_register_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

var File_proto_request_register_proto protoreflect.FileDescriptor

const file_proto_request_register_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/request/register.proto\x12\arequest\"\x86\x01\n" +
	"\x13UserRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumberB5Z3github.com/credstack/credstack-models/proto/requestb\x06proto3"

var (
	file_proto_request_register_proto_rawDescOnce sync.Once
	file_proto_request_register_proto_rawDescData []byte
)

func file_proto_request_register_proto_rawDescGZIP() []byte {
	file_proto_request_register_proto_rawDescOnce.Do(func() {
		file_proto_request_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_request_register_proto_rawDesc), len(file_proto_request_register_proto_rawDesc)))
	})
	return file_proto_request_register_proto_rawDescData
}

var file_proto_request_register_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_request_register_proto_goTypes = []any{
	(*UserRegisterRequest)(nil), // 0: request.UserRegisterRequest
}
var file_proto_request_register_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_request_register_proto_init() }
func file_proto_request_register_proto_init() {
	if File_proto_request_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_request_register_proto_rawDesc), len(file_proto_request_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_request_register_proto_goTypes,
		DependencyIndexes: file_proto_request_register_proto_depIdxs,
		MessageInfos:      file_proto_request_register_proto_msgTypes,
	}.Build()
	File_proto_request_register_proto = out.File
	file_proto_request_register_proto_goTypes = nil
	file_proto_request_register_proto_depIdxs = nil
}
