// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/request/token.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenRequest - Universal token request model for use in: Client credentials flow, authorization code flow, and
// password grant flow
type TokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// grant_type - Describes the type of OAuth grant flow you are using
	GrantType string `protobuf:"bytes,1,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty" bson:"grant_type" query:"grant_type"` // @gotags: bson:"grant_type" query:"grant_type"
	// client_id - The client id of the application. Can be null in some cases
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty" bson:"client_id" query:"client_id"` // @gotags: bson:"client_id" query:"client_id"
	// client_secret - The client secret of the application. Can be null in some cases
	ClientSecret string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty" bson:"client_secret" query:"client_secret"` // @gotags: bson:"client_secret" query:"client_secret"
	// audience - The audience for the API you are requesting a token for
	Audience string `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty" bson:"audience" query:"audience"` // @gotags: bson:"audience" query:"audience"
	// code - The code used in Authorization Code flow
	Code string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty" bson:"code" query:"code"` // @gotags: bson:"code" query:"code"
	// redirect_uri - The redirect URI used in Authorization code flow
	RedirectUri   string `protobuf:"bytes,6,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty" bson:"redirect_uri" query:"redirect_uri"` // @gotags: bson:"redirect_uri" query:"redirect_uri"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_proto_request_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_request_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_request_token_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *TokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TokenRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *TokenRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *TokenRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TokenRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

var File_proto_request_token_proto protoreflect.FileDescriptor

const file_proto_request_token_proto_rawDesc = "" +
	"\n" +
	"\x19proto/request/token.proto\x12\arequest\"\xc2\x01\n" +
	"\fTokenRequest\x12\x1d\n" +
	"\n" +
	"grant_type\x18\x01 \x01(\tR\tgrantType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x12\x1a\n" +
	"\baudience\x18\x04 \x01(\tR\baudience\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12!\n" +
	"\fredirect_uri\x18\x06 \x01(\tR\vredirectUriB5Z3github.com/credstack/credstack-models/proto/requestb\x06proto3"

var (
	file_proto_request_token_proto_rawDescOnce sync.Once
	file_proto_request_token_proto_rawDescData []byte
)

func file_proto_request_token_proto_rawDescGZIP() []byte {
	file_proto_request_token_proto_rawDescOnce.Do(func() {
		file_proto_request_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_request_token_proto_rawDesc), len(file_proto_request_token_proto_rawDesc)))
	})
	return file_proto_request_token_proto_rawDescData
}

var file_proto_request_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_request_token_proto_goTypes = []any{
	(*TokenRequest)(nil), // 0: request.TokenRequest
}
var file_proto_request_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_request_token_proto_init() }
func file_proto_request_token_proto_init() {
	if File_proto_request_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_request_token_proto_rawDesc), len(file_proto_request_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_request_token_proto_goTypes,
		DependencyIndexes: file_proto_request_token_proto_depIdxs,
		MessageInfos:      file_proto_request_token_proto_msgTypes,
	}.Build()
	File_proto_request_token_proto = out.File
	file_proto_request_token_proto_goTypes = nil
	file_proto_request_token_proto_depIdxs = nil
}
