// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/jwk/jwk.proto

package key

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JSONWebKey - A simple structure representing a public JSON Web Key
type JSONWebKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kty - Defines the type of key this JWK represents
	Kty string `protobuf:"bytes,1,opt,name=kty,proto3" json:"kty,omitempty" bson:"kty"` // @gotags: bson:"kty"
	// use - Defines the use for this JWK, usually sig
	Use string `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty" bson:"use"` // @gotags: bson:"use"
	// kid - A unique identifier for the key
	Kid string `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty" bson:"kid"` // @gotags: bson:"kid"
	// alg - Defines the algorithm that this JWK was generated using
	Alg string `protobuf:"bytes,4,opt,name=alg,proto3" json:"alg,omitempty" bson:"alg"` // @gotags: bson:"alg"
	// n - Public modulos for the key
	N string `protobuf:"bytes,5,opt,name=n,proto3" json:"n,omitempty" bson:"n"` // @gotags: bson:"n"
	// e - Public exponent for the key
	E             string `protobuf:"bytes,6,opt,name=e,proto3" json:"e,omitempty" bson:"e"` // @gotags: bson:"e"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONWebKey) Reset() {
	*x = JSONWebKey{}
	mi := &file_proto_jwk_jwk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONWebKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONWebKey) ProtoMessage() {}

func (x *JSONWebKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jwk_jwk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONWebKey.ProtoReflect.Descriptor instead.
func (*JSONWebKey) Descriptor() ([]byte, []int) {
	return file_proto_jwk_jwk_proto_rawDescGZIP(), []int{0}
}

func (x *JSONWebKey) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *JSONWebKey) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *JSONWebKey) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *JSONWebKey) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *JSONWebKey) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *JSONWebKey) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

var File_proto_jwk_jwk_proto protoreflect.FileDescriptor

const file_proto_jwk_jwk_proto_rawDesc = "" +
	"\n" +
	"\x13proto/jwk/jwk.proto\x12\x03jwk\"p\n" +
	"\n" +
	"JSONWebKey\x12\x10\n" +
	"\x03kty\x18\x01 \x01(\tR\x03kty\x12\x10\n" +
	"\x03use\x18\x02 \x01(\tR\x03use\x12\x10\n" +
	"\x03kid\x18\x03 \x01(\tR\x03kid\x12\x10\n" +
	"\x03alg\x18\x04 \x01(\tR\x03alg\x12\f\n" +
	"\x01n\x18\x05 \x01(\tR\x01n\x12\f\n" +
	"\x01e\x18\x06 \x01(\tR\x01eB1Z/github.com/credstack/credstack-models/proto/keyb\x06proto3"

var (
	file_proto_jwk_jwk_proto_rawDescOnce sync.Once
	file_proto_jwk_jwk_proto_rawDescData []byte
)

func file_proto_jwk_jwk_proto_rawDescGZIP() []byte {
	file_proto_jwk_jwk_proto_rawDescOnce.Do(func() {
		file_proto_jwk_jwk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_jwk_jwk_proto_rawDesc), len(file_proto_jwk_jwk_proto_rawDesc)))
	})
	return file_proto_jwk_jwk_proto_rawDescData
}

var file_proto_jwk_jwk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_jwk_jwk_proto_goTypes = []any{
	(*JSONWebKey)(nil), // 0: jwk.JSONWebKey
}
var file_proto_jwk_jwk_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_jwk_jwk_proto_init() }
func file_proto_jwk_jwk_proto_init() {
	if File_proto_jwk_jwk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_jwk_jwk_proto_rawDesc), len(file_proto_jwk_jwk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_jwk_jwk_proto_goTypes,
		DependencyIndexes: file_proto_jwk_jwk_proto_depIdxs,
		MessageInfos:      file_proto_jwk_jwk_proto_msgTypes,
	}.Build()
	File_proto_jwk_jwk_proto = out.File
	file_proto_jwk_jwk_proto_goTypes = nil
	file_proto_jwk_jwk_proto_depIdxs = nil
}
