// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/jwk/private.proto

package key

import (
	header "github.com/credstack/credstack-models/proto/header"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PrivateJSONWebKey - Represents a encryption key that can be used for signing tokens. This model can be used for both
// RS tokens and HS tokens
type PrivateJSONWebKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// header - The generated header for the key pair
	Header *header.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty" bson:"header"` // @gotags: bson:"header"
	// alg - Specify's the algorithm used for generating the key
	Alg string `protobuf:"bytes,2,opt,name=alg,proto3" json:"alg,omitempty" bson:"alg"` // @gotags: bson:"alg"
	// key_material - The PEM encoded private key
	KeyMaterial string `protobuf:"bytes,3,opt,name=key_material,json=keyMaterial,proto3" json:"key_material,omitempty" bson:"key_material"` // @gotags: bson:"key_material"
	// size - The size of the key in bits
	Size int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty" bson:"size"` // @gotags: bson:"size"
	// is_current - If set to true, then this key is selected for signing tokens
	IsCurrent bool `protobuf:"varint,5,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty" bson:"is_current"` // @gotags: bson:"is_current"
	// audience - The audience of the API that this key was allocated for
	Audience      string `protobuf:"bytes,6,opt,name=audience,proto3" json:"audience,omitempty" bson:"audience"` // @gotags: bson:"audience"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateJSONWebKey) Reset() {
	*x = PrivateJSONWebKey{}
	mi := &file_proto_jwk_private_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateJSONWebKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateJSONWebKey) ProtoMessage() {}

func (x *PrivateJSONWebKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jwk_private_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateJSONWebKey.ProtoReflect.Descriptor instead.
func (*PrivateJSONWebKey) Descriptor() ([]byte, []int) {
	return file_proto_jwk_private_proto_rawDescGZIP(), []int{0}
}

func (x *PrivateJSONWebKey) GetHeader() *header.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PrivateJSONWebKey) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *PrivateJSONWebKey) GetKeyMaterial() string {
	if x != nil {
		return x.KeyMaterial
	}
	return ""
}

func (x *PrivateJSONWebKey) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PrivateJSONWebKey) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *PrivateJSONWebKey) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

var File_proto_jwk_private_proto protoreflect.FileDescriptor

const file_proto_jwk_private_proto_rawDesc = "" +
	"\n" +
	"\x17proto/jwk/private.proto\x12\x03jwk\x1a\x19proto/header/header.proto\"\xbf\x01\n" +
	"\x11PrivateJSONWebKey\x12&\n" +
	"\x06header\x18\x01 \x01(\v2\x0e.header.HeaderR\x06header\x12\x10\n" +
	"\x03alg\x18\x02 \x01(\tR\x03alg\x12!\n" +
	"\fkey_material\x18\x03 \x01(\tR\vkeyMaterial\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"is_current\x18\x05 \x01(\bR\tisCurrent\x12\x1a\n" +
	"\baudience\x18\x06 \x01(\tR\baudienceB1Z/github.com/credstack/credstack-models/proto/keyb\x06proto3"

var (
	file_proto_jwk_private_proto_rawDescOnce sync.Once
	file_proto_jwk_private_proto_rawDescData []byte
)

func file_proto_jwk_private_proto_rawDescGZIP() []byte {
	file_proto_jwk_private_proto_rawDescOnce.Do(func() {
		file_proto_jwk_private_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_jwk_private_proto_rawDesc), len(file_proto_jwk_private_proto_rawDesc)))
	})
	return file_proto_jwk_private_proto_rawDescData
}

var file_proto_jwk_private_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_jwk_private_proto_goTypes = []any{
	(*PrivateJSONWebKey)(nil), // 0: jwk.PrivateJSONWebKey
	(*header.Header)(nil),     // 1: header.Header
}
var file_proto_jwk_private_proto_depIdxs = []int32{
	1, // 0: jwk.PrivateJSONWebKey.header:type_name -> header.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_jwk_private_proto_init() }
func file_proto_jwk_private_proto_init() {
	if File_proto_jwk_private_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_jwk_private_proto_rawDesc), len(file_proto_jwk_private_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_jwk_private_proto_goTypes,
		DependencyIndexes: file_proto_jwk_private_proto_depIdxs,
		MessageInfos:      file_proto_jwk_private_proto_msgTypes,
	}.Build()
	File_proto_jwk_private_proto = out.File
	file_proto_jwk_private_proto_goTypes = nil
	file_proto_jwk_private_proto_depIdxs = nil
}
