// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/token/introspect.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenIntrospectResponse - Represents a response from the endpoint /oauth/introspect
type TokenIntrospectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// active - A boolean value that determines if the token is active or not
	Active bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty" bson:"active"` // @gotags: bson:"active"
	// client_id - The client identifier for the application that issued the token
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty" bson:"client_id"` // @gotags: bson:"client_id"
	// sub - The subject of who the token was issued for. Can be a username or client id if client credentials flow was used
	Sub string `protobuf:"bytes,3,opt,name=sub,proto3" json:"sub,omitempty" bson:"sub"` // @gotags: bson:"sub"
	// scope - Any scopes that were issued with the token
	Scope string `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty" bson:"scope"` // @gotags: bson:"scope"
	// exp - A unix timestamp representing the tokens expiration date
	Exp           int64 `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty" bson:"exp"` // @gotags: bson:"exp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenIntrospectResponse) Reset() {
	*x = TokenIntrospectResponse{}
	mi := &file_proto_token_introspect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIntrospectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIntrospectResponse) ProtoMessage() {}

func (x *TokenIntrospectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_introspect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIntrospectResponse.ProtoReflect.Descriptor instead.
func (*TokenIntrospectResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_introspect_proto_rawDescGZIP(), []int{0}
}

func (x *TokenIntrospectResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *TokenIntrospectResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TokenIntrospectResponse) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *TokenIntrospectResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *TokenIntrospectResponse) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

var File_proto_token_introspect_proto protoreflect.FileDescriptor

const file_proto_token_introspect_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/token/introspect.proto\x12\x05token\"\x88\x01\n" +
	"\x17TokenIntrospectResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x10\n" +
	"\x03sub\x18\x03 \x01(\tR\x03sub\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x03R\x03expB3Z1github.com/credstack/credstack-models/proto/tokenb\x06proto3"

var (
	file_proto_token_introspect_proto_rawDescOnce sync.Once
	file_proto_token_introspect_proto_rawDescData []byte
)

func file_proto_token_introspect_proto_rawDescGZIP() []byte {
	file_proto_token_introspect_proto_rawDescOnce.Do(func() {
		file_proto_token_introspect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_introspect_proto_rawDesc), len(file_proto_token_introspect_proto_rawDesc)))
	})
	return file_proto_token_introspect_proto_rawDescData
}

var file_proto_token_introspect_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_token_introspect_proto_goTypes = []any{
	(*TokenIntrospectResponse)(nil), // 0: token.TokenIntrospectResponse
}
var file_proto_token_introspect_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_token_introspect_proto_init() }
func file_proto_token_introspect_proto_init() {
	if File_proto_token_introspect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_introspect_proto_rawDesc), len(file_proto_token_introspect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_token_introspect_proto_goTypes,
		DependencyIndexes: file_proto_token_introspect_proto_depIdxs,
		MessageInfos:      file_proto_token_introspect_proto_msgTypes,
	}.Build()
	File_proto_token_introspect_proto = out.File
	file_proto_token_introspect_proto_goTypes = nil
	file_proto_token_introspect_proto_depIdxs = nil
}
