// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/token/response.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenResponse - Represents an HTTP response containing the credentials requested by the end user
type TokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// access_token - The JWT token as returned by the application
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty" bson:"access_token"` // @gotags: bson:"access_token"
	// id_token - The JWT token as returned by the application
	IdToken string `protobuf:"bytes,2,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty" bson:"id_token"` // @gotags: bson:"id_token"
	// token_type - The type of token this response represents. Usually bearer
	TokenType string `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty" bson:"token_type"` // @gotags: bson:"token_type"
	// expires_in - The time in seconds that the token expires in
	ExpiresIn uint32 `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty" bson:"expires_in"` // @gotags: bson:"expires_in"
	// refresh_token - The refresh token that the application has issued
	RefreshToken string `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty" bson:"refresh_token"` // @gotags: bson:"refresh_token"
	// scope - A string of space seperated scopes that the user has been issued
	Scope         string `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty" bson:"scope"` // @gotags: bson:"scope"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_proto_token_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_response_proto_rawDescGZIP(), []int{0}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResponse) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *TokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenResponse) GetExpiresIn() uint32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

var File_proto_token_response_proto protoreflect.FileDescriptor

const file_proto_token_response_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/token/response.proto\x12\x05token\"\xc6\x01\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x19\n" +
	"\bid_token\x18\x02 \x01(\tR\aidToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\rR\texpiresIn\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scopeB3Z1github.com/credstack/credstack-models/proto/tokenb\x06proto3"

var (
	file_proto_token_response_proto_rawDescOnce sync.Once
	file_proto_token_response_proto_rawDescData []byte
)

func file_proto_token_response_proto_rawDescGZIP() []byte {
	file_proto_token_response_proto_rawDescOnce.Do(func() {
		file_proto_token_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_response_proto_rawDesc), len(file_proto_token_response_proto_rawDesc)))
	})
	return file_proto_token_response_proto_rawDescData
}

var file_proto_token_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_token_response_proto_goTypes = []any{
	(*TokenResponse)(nil), // 0: token.TokenResponse
}
var file_proto_token_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_token_response_proto_init() }
func file_proto_token_response_proto_init() {
	if File_proto_token_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_response_proto_rawDesc), len(file_proto_token_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_token_response_proto_goTypes,
		DependencyIndexes: file_proto_token_response_proto_depIdxs,
		MessageInfos:      file_proto_token_response_proto_msgTypes,
	}.Build()
	File_proto_token_response_proto = out.File
	file_proto_token_response_proto_goTypes = nil
	file_proto_token_response_proto_depIdxs = nil
}
