// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenType - The type of tokens the API should issue
type TokenType int32

const (
	TokenType_HS256 TokenType = 0
	TokenType_RS256 TokenType = 1
)

// Enum value maps for TokenType.
var (
	TokenType_name = map[int32]string{
		0: "HS256",
		1: "RS256",
	}
	TokenType_value = map[string]int32{
		"HS256": 0,
		"RS256": 1,
	}
)

func (x TokenType) Enum() *TokenType {
	p := new(TokenType)
	*p = x
	return p
}

func (x TokenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_api_proto_enumTypes[0].Descriptor()
}

func (TokenType) Type() protoreflect.EnumType {
	return &file_proto_api_api_proto_enumTypes[0]
}

func (x TokenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenType.Descriptor instead.
func (TokenType) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_api_proto_rawDescGZIP(), []int{0}
}

// API - Represents an integrators API. Primarily contains RBAC information and determines the token type
type API struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// domain - A arbitrary domain used in the audience of issues tokens. Does not need to resolve to anything
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// name - The name of the API as defined by the user
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// token_type - The type of tokens the API should issue
	TokenType TokenType `protobuf:"varint,3,opt,name=token_type,json=tokenType,proto3,enum=api.TokenType" json:"token_type,omitempty"`
	// enforce_rbac - Enforce permissions and roles for this API
	EnforceRbac bool `protobuf:"varint,4,opt,name=enforce_rbac,json=enforceRbac,proto3" json:"enforce_rbac,omitempty"`
	// applications - A list of authorized applications for this API
	Applications  []string `protobuf:"bytes,5,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *API) Reset() {
	*x = API{}
	mi := &file_proto_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *API) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*API) ProtoMessage() {}

func (x *API) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use API.ProtoReflect.Descriptor instead.
func (*API) Descriptor() ([]byte, []int) {
	return file_proto_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *API) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *API) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *API) GetTokenType() TokenType {
	if x != nil {
		return x.TokenType
	}
	return TokenType_HS256
}

func (x *API) GetEnforceRbac() bool {
	if x != nil {
		return x.EnforceRbac
	}
	return false
}

func (x *API) GetApplications() []string {
	if x != nil {
		return x.Applications
	}
	return nil
}

var File_proto_api_api_proto protoreflect.FileDescriptor

const file_proto_api_api_proto_rawDesc = "" +
	"\n" +
	"\x13proto/api/api.proto\x12\x03api\"\xa7\x01\n" +
	"\x03API\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\n" +
	"token_type\x18\x03 \x01(\x0e2\x0e.api.TokenTypeR\ttokenType\x12!\n" +
	"\fenforce_rbac\x18\x04 \x01(\bR\venforceRbac\x12\"\n" +
	"\fapplications\x18\x05 \x03(\tR\fapplications*!\n" +
	"\tTokenType\x12\t\n" +
	"\x05HS256\x10\x00\x12\t\n" +
	"\x05RS256\x10\x01B2Z0github.com/stevezaluk/credstack-models/proto/apib\x06proto3"

var (
	file_proto_api_api_proto_rawDescOnce sync.Once
	file_proto_api_api_proto_rawDescData []byte
)

func file_proto_api_api_proto_rawDescGZIP() []byte {
	file_proto_api_api_proto_rawDescOnce.Do(func() {
		file_proto_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_api_proto_rawDesc), len(file_proto_api_api_proto_rawDesc)))
	})
	return file_proto_api_api_proto_rawDescData
}

var file_proto_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_api_api_proto_goTypes = []any{
	(TokenType)(0), // 0: api.TokenType
	(*API)(nil),    // 1: api.API
}
var file_proto_api_api_proto_depIdxs = []int32{
	0, // 0: api.API.token_type:type_name -> api.TokenType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_api_api_proto_init() }
func file_proto_api_api_proto_init() {
	if File_proto_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_api_proto_rawDesc), len(file_proto_api_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_api_proto_goTypes,
		DependencyIndexes: file_proto_api_api_proto_depIdxs,
		EnumInfos:         file_proto_api_api_proto_enumTypes,
		MessageInfos:      file_proto_api_api_proto_msgTypes,
	}.Build()
	File_proto_api_api_proto = out.File
	file_proto_api_api_proto_goTypes = nil
	file_proto_api_api_proto_depIdxs = nil
}
