// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/api/scope.proto

package api

import (
	header "github.com/stevezaluk/credstack-models/header"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PermissionScope - A structure representing a unit of permissions that can be evaluated by the API.
// When marshaled and returned to the user, key and value are appended together in the following format:
//
// `key:value`
type PermissionScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// header - Shared data values used across all objects
	Header *header.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// associated_api - The API this permission scope is assigned to
	AssociatedApi string `protobuf:"bytes,2,opt,name=associated_api,json=associatedApi,proto3" json:"associated_api,omitempty"`
	// key - A key for the permission scope
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// value - A value for the permission scope
	Value         string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionScope) Reset() {
	*x = PermissionScope{}
	mi := &file_proto_api_scope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionScope) ProtoMessage() {}

func (x *PermissionScope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_scope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionScope.ProtoReflect.Descriptor instead.
func (*PermissionScope) Descriptor() ([]byte, []int) {
	return file_proto_api_scope_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionScope) GetHeader() *header.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PermissionScope) GetAssociatedApi() string {
	if x != nil {
		return x.AssociatedApi
	}
	return ""
}

func (x *PermissionScope) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PermissionScope) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_api_scope_proto protoreflect.FileDescriptor

const file_proto_api_scope_proto_rawDesc = "" +
	"\n" +
	"\x15proto/api/scope.proto\x12\x03api\x1a\x19proto/header/header.proto\"\x88\x01\n" +
	"\x0fPermissionScope\x12&\n" +
	"\x06header\x18\x01 \x01(\v2\x0e.header.HeaderR\x06header\x12%\n" +
	"\x0eassociated_api\x18\x02 \x01(\tR\rassociatedApi\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05valueB,Z*github.com/stevezaluk/credstack-models/apib\x06proto3"

var (
	file_proto_api_scope_proto_rawDescOnce sync.Once
	file_proto_api_scope_proto_rawDescData []byte
)

func file_proto_api_scope_proto_rawDescGZIP() []byte {
	file_proto_api_scope_proto_rawDescOnce.Do(func() {
		file_proto_api_scope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_scope_proto_rawDesc), len(file_proto_api_scope_proto_rawDesc)))
	})
	return file_proto_api_scope_proto_rawDescData
}

var file_proto_api_scope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_api_scope_proto_goTypes = []any{
	(*PermissionScope)(nil), // 0: api.PermissionScope
	(*header.Header)(nil),   // 1: header.Header
}
var file_proto_api_scope_proto_depIdxs = []int32{
	1, // 0: api.PermissionScope.header:type_name -> header.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_api_scope_proto_init() }
func file_proto_api_scope_proto_init() {
	if File_proto_api_scope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_scope_proto_rawDesc), len(file_proto_api_scope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_scope_proto_goTypes,
		DependencyIndexes: file_proto_api_scope_proto_depIdxs,
		MessageInfos:      file_proto_api_scope_proto_msgTypes,
	}.Build()
	File_proto_api_scope_proto = out.File
	file_proto_api_scope_proto_goTypes = nil
	file_proto_api_scope_proto_depIdxs = nil
}
