// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/header/header.proto

package header

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Header - A message representing shared data that is applied to all objects created by credstack
type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// createdAt - A unix timestamp representing when the object was created
	CreatedAt int64 `protobuf:"varint,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt - A unix timestamp representing when the object was last updated
	UpdatedAt int64 `protobuf:"varint,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	// accessedAt - A unix timestamp representing when the object was last accessed
	AccessedAt int64 `protobuf:"varint,3,opt,name=accessedAt,proto3" json:"accessedAt,omitempty"`
	// tags - Arbitrary tags that can be applied to any object
	Tags          map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_header_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_header_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_header_header_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Header) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Header) GetAccessedAt() int64 {
	if x != nil {
		return x.AccessedAt
	}
	return 0
}

func (x *Header) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_proto_header_header_proto protoreflect.FileDescriptor

const file_proto_header_header_proto_rawDesc = "" +
	"\n" +
	"\x19proto/header/header.proto\x12\x06header\"\xcb\x01\n" +
	"\x06Header\x12\x1c\n" +
	"\tcreatedAt\x18\x01 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x02 \x01(\x03R\tupdatedAt\x12\x1e\n" +
	"\n" +
	"accessedAt\x18\x03 \x01(\x03R\n" +
	"accessedAt\x12,\n" +
	"\x04tags\x18\x04 \x03(\v2\x18.header.Header.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-github.com/stevezaluk/credstack-models/headerb\x06proto3"

var (
	file_proto_header_header_proto_rawDescOnce sync.Once
	file_proto_header_header_proto_rawDescData []byte
)

func file_proto_header_header_proto_rawDescGZIP() []byte {
	file_proto_header_header_proto_rawDescOnce.Do(func() {
		file_proto_header_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_header_header_proto_rawDesc), len(file_proto_header_header_proto_rawDesc)))
	})
	return file_proto_header_header_proto_rawDescData
}

var file_proto_header_header_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_header_header_proto_goTypes = []any{
	(*Header)(nil), // 0: header.Header
	nil,            // 1: header.Header.TagsEntry
}
var file_proto_header_header_proto_depIdxs = []int32{
	1, // 0: header.Header.tags:type_name -> header.Header.TagsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_header_header_proto_init() }
func file_proto_header_header_proto_init() {
	if File_proto_header_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_header_header_proto_rawDesc), len(file_proto_header_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_header_header_proto_goTypes,
		DependencyIndexes: file_proto_header_header_proto_depIdxs,
		MessageInfos:      file_proto_header_header_proto_msgTypes,
	}.Build()
	File_proto_header_header_proto = out.File
	file_proto_header_header_proto_goTypes = nil
	file_proto_header_header_proto_depIdxs = nil
}
