// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/application/application.proto

package application

import (
	header "github.com/stevezaluk/credstack-models/header"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GrantTypes - A list of enums representing an OAuth Grant Type
type GrantTypes int32

const (
	// ClientCredentialsGrant - Client credentials grant allows direct issuance of tokens in exchange for a client ID and secret
	GrantTypes_ClientCredentialsGrant GrantTypes = 0
	// AuthorizationCodeGrant - Authorization Code Grant + PKCE allows tokens to be issued after the user has authentication with an OIDC provider
	GrantTypes_AuthorizationCodeGrant GrantTypes = 1
	// PasswordGrant - Deprecated OAuth grant that allows direct issuance of tokens in exchange for raw user credentials
	GrantTypes_PasswordGrant GrantTypes = 2
)

// Enum value maps for GrantTypes.
var (
	GrantTypes_name = map[int32]string{
		0: "ClientCredentialsGrant",
		1: "AuthorizationCodeGrant",
		2: "PasswordGrant",
	}
	GrantTypes_value = map[string]int32{
		"ClientCredentialsGrant": 0,
		"AuthorizationCodeGrant": 1,
		"PasswordGrant":          2,
	}
)

func (x GrantTypes) Enum() *GrantTypes {
	p := new(GrantTypes)
	*p = x
	return p
}

func (x GrantTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GrantTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_application_application_proto_enumTypes[0].Descriptor()
}

func (GrantTypes) Type() protoreflect.EnumType {
	return &file_proto_application_application_proto_enumTypes[0]
}

func (x GrantTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GrantTypes.Descriptor instead.
func (GrantTypes) EnumDescriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{0}
}

// Application - The core resource allowing that provides the issuance of tokens
type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// header - Shared data values used across all objects
	Header *header.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// clientId - The client ID used in the authorization process
	ClientId string `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	// clientSecret - The client secret used in the authorization process
	ClientSecret string `protobuf:"bytes,3,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	// redirectUri - A redirect URI for the application to redirect to after authorization
	RedirectUri string `protobuf:"bytes,4,opt,name=redirectUri,proto3" json:"redirectUri,omitempty"`
	// tokenLifetime - The amount of time in seconds, before the token expires
	TokenLifetime uint64 `protobuf:"varint,5,opt,name=tokenLifetime,proto3" json:"tokenLifetime,omitempty"`
	// grantType - The grant types this Application is authorized to issue on
	GrantTypes    []GrantTypes `protobuf:"varint,6,rep,packed,name=grantTypes,proto3,enum=application.GrantTypes" json:"grantTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_proto_application_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_proto_application_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_proto_application_application_proto_rawDescGZIP(), []int{0}
}

func (x *Application) GetHeader() *header.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Application) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Application) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *Application) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *Application) GetTokenLifetime() uint64 {
	if x != nil {
		return x.TokenLifetime
	}
	return 0
}

func (x *Application) GetGrantTypes() []GrantTypes {
	if x != nil {
		return x.GrantTypes
	}
	return nil
}

var File_proto_application_application_proto protoreflect.FileDescriptor

const file_proto_application_application_proto_rawDesc = "" +
	"\n" +
	"#proto/application/application.proto\x12\vapplication\x1a\x19proto/header/header.proto\"\xf6\x01\n" +
	"\vApplication\x12&\n" +
	"\x06header\x18\x01 \x01(\v2\x0e.header.HeaderR\x06header\x12\x1a\n" +
	"\bclientId\x18\x02 \x01(\tR\bclientId\x12\"\n" +
	"\fclientSecret\x18\x03 \x01(\tR\fclientSecret\x12 \n" +
	"\vredirectUri\x18\x04 \x01(\tR\vredirectUri\x12$\n" +
	"\rtokenLifetime\x18\x05 \x01(\x04R\rtokenLifetime\x127\n" +
	"\n" +
	"grantTypes\x18\x06 \x03(\x0e2\x17.application.GrantTypesR\n" +
	"grantTypes*W\n" +
	"\n" +
	"GrantTypes\x12\x1a\n" +
	"\x16ClientCredentialsGrant\x10\x00\x12\x1a\n" +
	"\x16AuthorizationCodeGrant\x10\x01\x12\x11\n" +
	"\rPasswordGrant\x10\x02B4Z2github.com/stevezaluk/credstack-models/applicationb\x06proto3"

var (
	file_proto_application_application_proto_rawDescOnce sync.Once
	file_proto_application_application_proto_rawDescData []byte
)

func file_proto_application_application_proto_rawDescGZIP() []byte {
	file_proto_application_application_proto_rawDescOnce.Do(func() {
		file_proto_application_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_application_application_proto_rawDesc), len(file_proto_application_application_proto_rawDesc)))
	})
	return file_proto_application_application_proto_rawDescData
}

var file_proto_application_application_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_application_application_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_application_application_proto_goTypes = []any{
	(GrantTypes)(0),       // 0: application.GrantTypes
	(*Application)(nil),   // 1: application.Application
	(*header.Header)(nil), // 2: header.Header
}
var file_proto_application_application_proto_depIdxs = []int32{
	2, // 0: application.Application.header:type_name -> header.Header
	0, // 1: application.Application.grantTypes:type_name -> application.GrantTypes
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_application_application_proto_init() }
func file_proto_application_application_proto_init() {
	if File_proto_application_application_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_application_application_proto_rawDesc), len(file_proto_application_application_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_application_application_proto_goTypes,
		DependencyIndexes: file_proto_application_application_proto_depIdxs,
		EnumInfos:         file_proto_application_application_proto_enumTypes,
		MessageInfos:      file_proto_application_application_proto_msgTypes,
	}.Build()
	File_proto_application_application_proto = out.File
	file_proto_application_application_proto_goTypes = nil
	file_proto_application_application_proto_depIdxs = nil
}
