// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/user/user.proto

package user

import (
	header "github.com/stevezaluk/credstack-models/header"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User - Represents a user registered with CredStack. Describes all standard claims for the OpenID Connect spec
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// header - Shared data values used across all objects
	Header *header.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// sub - A UUID v5 based on the users email address, used for identifying the user
	Sub string `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	// username - The username of the user. Does not need to be unique as primary lookup for the user is done via userId
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// email - The primary email address for the user. Must be unique
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// emailVerified - A boolean value describing if the user has validated there email address
	EmailVerified bool `protobuf:"varint,5,opt,name=emailVerified,proto3" json:"emailVerified,omitempty"`
	// givenName - The users first name. Can be null, and does not need to be unique
	GivenName string `protobuf:"bytes,6,opt,name=givenName,proto3" json:"givenName,omitempty"`
	// middleName - The users middle name. Can be null, and does not need to be unique
	MiddleName string `protobuf:"bytes,7,opt,name=middleName,proto3" json:"middleName,omitempty"`
	// familyName - The users last name. Can be null, and does not need to be unique
	FamilyName string `protobuf:"bytes,8,opt,name=familyName,proto3" json:"familyName,omitempty"`
	// gender - The users gender. Can be null
	Gender string `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	// birthDate - The users birthdate represented as YYYY-MM-DD
	BirthDate string `protobuf:"bytes,10,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	// zoneInfo - The timezone for the user that should be respected by timestamps. Defaults to America/New_York
	ZoneInfo string `protobuf:"bytes,11,opt,name=zoneInfo,proto3" json:"zoneInfo,omitempty"`
	// phoneNumber - The users phone number in the following format +1800-555-555
	PhoneNumber string `protobuf:"bytes,12,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	// phoneNumberVerified - A boolean value describing if the user has validated there email address
	PhoneNumberVerified string `protobuf:"bytes,13,opt,name=phoneNumberVerified,proto3" json:"phoneNumberVerified,omitempty"`
	// address - The users physical mailing address. Can be null
	Address string `protobuf:"bytes,14,opt,name=address,proto3" json:"address,omitempty"`
	// credential - A message representing the users hashed password. Will be left null when exporting unless explicitly declared
	Credential    *UserCredential `protobuf:"bytes,15,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetHeader() *header.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *User) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *User) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *User) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *User) GetZoneInfo() string {
	if x != nil {
		return x.ZoneInfo
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetPhoneNumberVerified() string {
	if x != nil {
		return x.PhoneNumberVerified
	}
	return ""
}

func (x *User) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *User) GetCredential() *UserCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

var File_proto_user_user_proto protoreflect.FileDescriptor

const file_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x15proto/user/user.proto\x12\x04user\x1a\x1bproto/user/credential.proto\x1a\x19proto/header/header.proto\"\xec\x03\n" +
	"\x04User\x12&\n" +
	"\x06header\x18\x01 \x01(\v2\x0e.header.HeaderR\x06header\x12\x10\n" +
	"\x03sub\x18\x02 \x01(\tR\x03sub\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12$\n" +
	"\remailVerified\x18\x05 \x01(\bR\remailVerified\x12\x1c\n" +
	"\tgivenName\x18\x06 \x01(\tR\tgivenName\x12\x1e\n" +
	"\n" +
	"middleName\x18\a \x01(\tR\n" +
	"middleName\x12\x1e\n" +
	"\n" +
	"familyName\x18\b \x01(\tR\n" +
	"familyName\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12\x1c\n" +
	"\tbirthDate\x18\n" +
	" \x01(\tR\tbirthDate\x12\x1a\n" +
	"\bzoneInfo\x18\v \x01(\tR\bzoneInfo\x12 \n" +
	"\vphoneNumber\x18\f \x01(\tR\vphoneNumber\x120\n" +
	"\x13phoneNumberVerified\x18\r \x01(\tR\x13phoneNumberVerified\x12\x18\n" +
	"\aaddress\x18\x0e \x01(\tR\aaddress\x124\n" +
	"\n" +
	"credential\x18\x0f \x01(\v2\x14.user.UserCredentialR\n" +
	"credentialB-Z+github.com/stevezaluk/credstack-models/userb\x06proto3"

var (
	file_proto_user_user_proto_rawDescOnce sync.Once
	file_proto_user_user_proto_rawDescData []byte
)

func file_proto_user_user_proto_rawDescGZIP() []byte {
	file_proto_user_user_proto_rawDescOnce.Do(func() {
		file_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)))
	})
	return file_proto_user_user_proto_rawDescData
}

var file_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_user_user_proto_goTypes = []any{
	(*User)(nil),           // 0: user.User
	(*header.Header)(nil),  // 1: header.Header
	(*UserCredential)(nil), // 2: user.UserCredential
}
var file_proto_user_user_proto_depIdxs = []int32{
	1, // 0: user.User.header:type_name -> header.Header
	2, // 1: user.User.credential:type_name -> user.UserCredential
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_user_user_proto_init() }
func file_proto_user_user_proto_init() {
	if File_proto_user_user_proto != nil {
		return
	}
	file_proto_user_credential_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_user_proto_goTypes,
		DependencyIndexes: file_proto_user_user_proto_depIdxs,
		MessageInfos:      file_proto_user_user_proto_msgTypes,
	}.Build()
	File_proto_user_user_proto = out.File
	file_proto_user_user_proto_goTypes = nil
	file_proto_user_user_proto_depIdxs = nil
}
